name: Build And Push Image to Development
on:
  push:
    branches:
      - notify

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          
      - name: Determine Version
        id: gitversion # id to later be referenced
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Display GitVersion outputs (step output)
        run: |
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "LegacySemVer: ${{ steps.gitversion.outputs.legacySemVer }}"
  
  build:
    runs-on: ubuntu-latest
    needs: versioning
    steps:
      - name: Notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            ${{ job.status == 'success' && '✅' || '🚨' }} *JOB: BUILD*
            
            *Status:* `${{ job.status }}`
            *Project:* `${{ github.repository }}`
            *Branch:* `${{ github.ref_name }}`
            *Commit:* [${{ github.event.head_commit.message }}](${{ github.event.head_commit.url }})
            
            [Перейти к логам сборки](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Telegram Notify Deploy
       if: always()
       uses: appleboy/telegram-action@master
       with:
         to: ${{ secrets.TG_CHAT_ID }}
         token: ${{ secrets.TG_TOKEN }}
         disable_web_page_preview: true
         format: markdown
         message: |
           ${{ job.status == 'success' && '🚀' || '🚨' }} *JOB: DEPLOY TO HERB-DEV1*
           
           *Status:* `${{ job.status }}`
           *Project:* `${{ github.repository }}`
           *Branch:* `${{ github.ref_name }}`
           *Environment:* [herb-dev1](https://herb-dev1.tproject.su)
           
           [Перейти к логам сборки](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})