name: Build And Push Image to Production
on:
  push:
    branches:
      - envs

  workflow_dispatch:
      inputs:
        environment:
          description: 'Выберите окружение для деплоя'
          required: true
          default: 'production'
          type: choice
          options:
            - rutime
            - cleverfoods

jobs:

  deploy:
      runs-on: ubuntu-latest
      environment: ${{ github.event.inputs.environment || 'rutime' }}

      steps:
        - name: Executing remote SSH commands
          run: |
            echo ${{ secrets.SSH_HOST }} 
            echo ${{ github.event.inputs.environment }}
            echo ${{ vars.SSH_HOST_TEST }}
            
