name: Build And Push Image to Production
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    types:
      - closed

jobs:
  versioning:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          
      - name: Determine Version
        id: gitversion # id to later be referenced
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Display GitVersion outputs (step output)
        run: |
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "LegacySemVer: ${{ steps.gitversion.outputs.legacySemVer }}"
  
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    needs: versioning
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_SECRET }}

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v
        with:
          context: ./app
          file: ./app/Dockerfile
          push: false
          tags: ghcr.io/tproject-s-u/rothb:${{ needs.versioning.outputs.semVer }}

  tagging:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    env:
      SEMVER: ${{ needs.versioning.outputs.semVer }}
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Tag and push current repo code
        run: |
          git tag $SEMVER
          git push origin $SEMVER
  
  bump_dev_version:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    needs: tagging
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - name: Configure git 
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Bump develop version
        run: |
          git commit --allow-empty -m "+bump: minor"
          git push origin develop
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Install SSH Key
  #       uses: shimataro/ssh-key-action@v2
  #       with:
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         name: id_rsa
  #         known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
  #         if_key_exists: replace

  #     - name: Adding Known Host
  #       run: ssh-keyscan -H ${{ secrets.SSH_HOST_PRD }} >> ~/.ssh/known_hosts

  #     - name: Try to Log In SSH
  #       run: ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_PRD }} 'bash ~/nordica/build_start.sh'
